### ISSUE TITLE
Totally blank

### ISSUE THREAD

**Issue by kaitmiller** [w11k/calendar-for-trello#112]
Calendar for Trello seems to have just updated to a new version (considering the completely different appearance and the popup at the bottom saying it's a new version) and I can't get anything to come up. It's just showing me a blank calendar.

**Comment by CanKattwinkel** [comment]
Hello @kaitmiller,

thank you for submitting your issue! The calendar was updated indeed. We are currently at Version 2.0.0-beta.4. The new beta replaces the old calendar with a way more efficient loading service. This was necessary since the calendar has so many users now, that it is acutally hitting the API limit of Trello. 

You probably already have, but try to use the "Clear Data" option in the upper right menu. If this doesnt work, try to renew your token by logging in and out. Please let us know if this solves your issue. 

We could only test our calendar with the latest versions of major browsers. Other fixes will follow. Could you please share some information about your browser and operating system? Also it would be nice if you could share 

Calendar-for-Trello was tested with the latest version of:
1. Edge
1. Mozilla
1. Chrome

**Comment by kaitmiller** [comment]
Thanks. I forgot that clicking "show cards of all members" is what worked
in previous versions. I tried Clear Data and logging in and out, but
neither of those worked--only "show cards of all members" did. (It's
possible I didn't see it yesterday because it was in German; I told Chrome
to translate it today.)

I'm not sure why "show cards of all members" should be relevant because
it's just me--I can't tell whether I've turned it on or off!

I'm using the latest version of Chrome on a Mac running OS X Yosemite.

Other than that, I really like the update :)

-Clare

**Comment by CanKattwinkel** [comment]
Per default only cards with your membership will be displayed. I'll change the default to showing all cards independent of the users membership in the next version.

**Comment by jblankenhorn** [comment]
Could this be extracted to a Setting, so users can define how to use this?

**Comment by kaitmiller** [comment]
Perhaps I should clarify that there are no shared cards on my Trello
boards. I don't currently have or work on any team boards; everything is on
my account alone, so "all cards with my membership" should be exactly
equivalent to "all cards independent over the user's membership."

And I'll also mention that the only reason that I have criticism is that I
LOVE and rely heavily on Calendar for Trello, so thank you so much! I
appreciate all your hard work on this great tool!

-Clare

**Comment by CanKattwinkel** [comment]
observermode is replaced with by per user filter in Beta.12, issue therefore closed.
