### ISSUE TITLE
Linking my Trello account.

### ISSUE THREAD

**Issue by FatGuyLaughing** [w11k/calendar-for-trello#134]
I have gone to https://trello.com/app-key and grabbed the first key at the top of the page labeled `Developer Key`. I've updated the file as explained in this [comment](https://github.com/w11k/calendar-for-trello/issues/133#issuecomment-276126566).

After this I ran `npm run start` and visited the localhost site. I don't currently see any of my cards. Is `Developer Key` the wrong key to use?

**Comment by CanKattwinkel** [comment]
No you proceed correct. Could you confirm that everything works in the [hosted version ](https://calendar-for-trello.com/)for you?     

If yes, please check: 
1. sign out from calendar at localhost:4200 (if you are currently logged in)
1. open your browsers developer console (Chrome: `CTRL` + `SHIFT` + `J`
1. do a new login at localhost:4200
1. check for errors appearing in the console

Submit upcoming errors here, but make sure to remove the token part from any URL since it is personal data.

**Comment by FatGuyLaughing** [comment]
> Response
> _body : "invalid token"
> headers : Headers
> ok : false
> status : 401
> statusText : "OK"
> type : 2
> url : "https://api.trello.com/1//members/me?key="
> \_\_proto\_\_ : Body

**Comment by FatGuyLaughing** [comment]
Under the `Developer Key` text box that holds the `key` I see a link that is for Token. Is this what I should be using?

<img width="617" alt="screen shot 2017-01-30 at 12 54 44 pm" src="https://cloud.githubusercontent.com/assets/405995/22436861/63e3f1ca-e6eb-11e6-9a37-f45a9ea15bfa.png">

**Comment by FatGuyLaughing** [comment]
Okay, so I just noticed I didn't edit both files as you explain before. Sorry for the mistake on my end.
