### ISSUE TITLE
Big Screens

### ISSUE THREAD

**Issue by jblankenhorn** [w11k/calendar-for-trello#138]
On big screens, the calendar takes too much width.
Can we introduce a max width?

![capturfiles-feb -01-2017_11 33 09](https://cloud.githubusercontent.com/assets/138586/22503640/efdad328-e872-11e6-8fbf-7224bb2e3fc1.png)

**Comment by CanKattwinkel** [comment]
Currently the max width is not a perfect solution since it looks weird with an open sidebar. How about enabling the sidebar per default on large screens?

![image](https://cloud.githubusercontent.com/assets/11500619/22508465/6970b4fc-e88a-11e6-81be-036a05114ede.png)
![image](https://cloud.githubusercontent.com/assets/11500619/22508473/71898ea2-e88a-11e6-989d-97774eb56c3c.png)

**Comment by jblankenhorn** [comment]
@CanKattwinkel not perfectly happy, but should be an improvement!
