### ISSUE TITLE
Feature Suggestion: Create Google Calendar Event from Trello Card

### ISSUE THREAD

**Issue by russellrosie** [w11k/calendar-for-trello#145]
The ability to manually create a calendar event from within the app.

e.g.
Calendar Event Title would default to card title.
Description would hold a URL for the trello card.
Calendar event would default to the due date.

Calendar event would not be automatically created but would simply pre-populate data on a new Google Calendar event that needs to be save by clicking button thereby allowing the user to schedule the action into their calendar at a time they are free.

**Comment by CanKattwinkel** [comment]
@jblankenhorn what do you think ?   (no google auth required)

The question is where to place the button since the space is limited.

Example:
https://www.google.com/calendar/render?action=TEMPLATE&text=Trello+Calendar+Example+Event&dates=20170215T224000Z/20170215T234000Z&details=Check+https://github.com/w11k/calendar-for-trello/issues/145&sf=true&output=xml

**Comment by jblankenhorn** [comment]
@CanKattwinkel i would prefer an iCal Feed from all your Cards to integrate in Google.
@niceaddress what do you think?

**Comment by niceaddress** [comment]
@jblankenhorn @CanKattwinkel

the example looks ideal! if i had that functionality available to me then all i would have to do is go to the 'find a time' tab to find an available slot in my calendar.

i'm sure i can't speak for everyone but maybe i can explain the way i use Trello to explain my use case. 

I have certain cards in Trello which represent actions and on those cards i use Due Date to reflect the deadline, but this deadline is the latest i could possibly finish this task in order for a project to stay on track.

But in order to hit that deadline i need to calendarize time to work on the task. e.g. suppose my deadline is 17:00 this friday then when i'm reviewing my tasks i would be reminded that the deadline is 17:00 and i might pop it into my calendar to work on the task on say Thursday morning when i have a free slot.
