### ISSUE TITLE
Calendar Settings Do Not Stick

### ISSUE THREAD

**Issue by MindyHanson** [w11k/calendar-for-trello#194]
When I set the language and day of the week I want my calendar to start on, it takes initially but then the setting return to the default. I will make a donation if we can rely on this tool... Please fix it!

**Comment by jblankenhorn** [comment]
Hi @MindyHanson ,

could you please tell me which browser you are using?
Did you try it in another Browser?
The settings are stored in the browser, do you have any browser plugin installed which may prevent this?

**Comment by CanKattwinkel** [comment]
What i could reproduce: While the start day of the week stays the same after a hard reload (F5) the language of the weekdays may change (for me back to german, even though the browser language and the setting are english). 

As Jan already pointed out each setting is only per browser. So if you switch computer the settings are "lost" since everything is only saved locally on your own computer!  

What you could try is to delete the calendars storage. Use the three dots in the upper right corner and select "Clear Data". Does the problem still occur? 

Thank you for reporting the error!

**Comment by hcflores** [comment]
I have the same issue. Using Chrome (Version 64.0.3282.140 (Official Build) (64-bit)), my "Language" and "Wekstart" settings only stay until I close my browser tab.  Once I come back to the site in a new tab, the settings revert to the default language and wekstart.

**Comment by jblankenhorn** [comment]
Hi @hcflores,

do you have somy Privacy addon installed?
