### ISSUE TITLE
Firefox - No option for Languagechange and Weekstart

### ISSUE THREAD

**Issue by Ollisterhase** [w11k/calendar-for-trello#227]
Hi,
I noticed that both the weekly start and the language is no longer selectable when I visit the Calendar-for-Trello with Firefox (version 61.0.2).  Everything works perfectly with Chrome.

**Comment by CanKattwinkel** [comment]
Hello @Ollisterhase, 

thanks for you bug report. This is correct. We removed the setting from the calendar since we are preparing a full localisation of the calendar in many languages. 

Your Chrome probably just holds an old version of the calendar that will be automatically be upgraded very soon.

So I'm gonna have to ask you to wait a few weeks until the full localisation is implemented and the calendar shows in the correct language with correct weekstart and date format for each country.

**Comment by jblankenhorn** [comment]
@Ollisterhase WeekStart is back again!

**Comment by Ollisterhase** [comment]
Very good. Thank you!
