### ISSUE TITLE
Are you working on a phone/tablet app for this?

### ISSUE THREAD

**Issue by blizzmonkey** [w11k/calendar-for-trello#54]
This works great on a computer, but when I use it in my phone browser it goes off the screen and can't be zoomed.  Seems like making it an app would be really useful.

**Comment by michaeloj** [comment]
- the calendar day does not show on mobile view
- Card not linked to Trello on mobile view
- Time cant be seen on mobile

I think lots of people want this app. But are you guys really serious in driving this forward?

**Comment by CanKattwinkel** [comment]
Thanks for your feedback! Due to our workload it is unlikely that we'll fix the mobile version in a short while. The focus is for desktop users since 90% use regular browsers. So you can expect a bugfix for the points named by @michaeloj after a while but right now we have no ambitions in creating a real mobile application. Maybe if more users need this. 
best regards can
