### ISSUE TITLE
Feature Idea

### ISSUE THREAD

**Issue by phsantiago** [w11k/calendar-for-trello#77]
A share link to current calendar can be very useful.

**Comment by CanKattwinkel** [comment]
Hello @phsantiago ,

could you clarify please what exactly you mean?:

a) A deep link to a current date? 
b) Or a link to the current view of cards?

We cant do **b** since the cards are loaded from your (private) personal account. Not even our server has access to the cards. Everything - expect the loading of our webapp - happens directly between you and Trello.

**Comment by CanKattwinkel** [comment]
Close due to inactivity..
