### ISSUE TITLE
Inconsistent loading

### ISSUE THREAD

**Issue by jordanlui** [w11k/calendar-for-trello#92]
Notice that on one machine (Chrome on Win 10 64 bit desktop) that all boards load. I can see all due dates for multiple different boards.

On another machine, only one board will load. Using Chrome or FireFox on Win 10 64 bit laptop. The other boards are visible on filter menu but their cards never show up.

Not sure how much detail you require. Curious if anyone else is encountering similar

**Comment by CanKattwinkel** [comment]
hi jordanlui,

could you please check your browsers developertools?


1. Open the developer tools by pressing F12 key in Firefox
2. go to calendar-for-trello.com 
3. check if there are any errors and if so, send uns a screenshot.



We experienced some issues with the Trello API Limit due to the increasing amount of users - this might be occurring sometimes. Currently we are developing a new version of our calendar. It is yet only a functional preview but take a look at:
w11k.github.io/calendar-for-trello/

**Comment by jordanlui** [comment]
Hi,
Here are screenshots when I access it in Firefox. Some issues in main.js.

![firefox_issues 1](https://cloud.githubusercontent.com/assets/10189567/20450684/0e25fa80-ada7-11e6-9469-6a0c5bb12f3c.png)
![firefox_issues 2](https://cloud.githubusercontent.com/assets/10189567/20450683/0e236c3e-ada7-11e6-9f19-0d47ec6f4606.png)


Here are some issues noted in Chrome. Issues are in month and main.js

![chrome issue](https://cloud.githubusercontent.com/assets/10189567/20450689/146a440a-ada7-11e6-9909-e1b0da80c88f.png)

I hope this helps!
Thanks,
Jordan

**Comment by CanKattwinkel** [comment]
Loading is fixed in the new version of the calendar. It is not yet released. 

You can preview the beta version here:
https://w11k.github.io/calendar-for-trello/

**Comment by jordanlui** [comment]
Working great in the new release. Thanks! :)
